### ISSUE TITLE
every time I open firefox

### ISSUE THREAD

**Issue by ledemon** [jscher2000/Prevent-Closing-Window#1]
Hi, every time I open firefox, the tab "Keep Open" load from nowhere with the description of the addon.

Thanks for the addon.

**Comment by jscher2000** [comment]
Yes, by design! That is the page where you can turn on protection if you want. _If you never want to turn on protection, you can uninstall the extension._

Eventually I hope to give you the option to only get the Keep Open page in private windows if you are not concerned about closing regular windows, but I haven't gotten around to it.
